# Generated by Django 3.2.9 on 2021-11-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=50)),
                ('medicine_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=30)),
                ('mfd', models.IntegerField(default=20)),
                ('expd', models.IntegerField(default=20)),
                ('price', models.IntegerField(default=30)),
            ],
        ),
    ]
