# Generated by Django 3.2.9 on 2021-11-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_pharmacymodel_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacymodel',
            name='Created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
