# Generated by Django 3.2.9 on 2021-11-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_adddepartmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddepartmentmodel',
            name='dept_name',
            field=models.CharField(max_length=80),
        ),
    ]
