# Generated by Django 3.2.9 on 2021-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_addappoinmentmodel_appoinment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addappoinmentmodel',
            name='appoinment_date',
            field=models.DateField(help_text='Please provide thedate in YY/MM/DD'),
        ),
    ]
