# Generated by Django 3.2.9 on 2021-12-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_adddepartmentmodel_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addappoinmentmodel',
            name='user',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='addleaveviewmodel',
            name='user',
            field=models.CharField(max_length=80),
        ),
    ]
