# Generated by Django 3.2.9 on 2021-12-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0011_auto_20211207_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='addappoinmentmodel',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
